# Generated by Django 4.2.23 on 2025-10-15 07:41

import crm.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DN_ID', models.CharField(default=crm.models.generate_dn_id, editable=False, max_length=20, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('delivery_type', models.CharField(choices=[('Regular', 'Regular'), ('Urgent', 'Urgent'), ('Return', 'Return')], default='Regular', max_length=20)),
                ('destination_address', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('Draft', 'Draft'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('partially_delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='delivery_note_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteCustomerAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='delivery_proof/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('uom', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNR_ID', models.CharField(default=crm.models.generate_delivery_note_return_id, editable=False, max_length=20, unique=True)),
                ('dnr_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='delivery_note_return_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('enquiry_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=50)),
                ('enquiry_description', models.TextField(blank=True)),
                ('enquiry_channels', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Web Form', 'Web Form'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('source', models.CharField(choices=[('WebSite', 'WebSite'), ('Referral', 'Referral'), ('Online Advertising', 'Online Advertising'), ('Offline Advertising', 'Offline Advertising'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('how_heard_this', models.CharField(blank=True, choices=[('WebSite', 'WebSite'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Event', 'Event'), ('Search Engine', 'Search Engine'), ('Other', 'Other')], max_length=50)),
                ('urgency_level', models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('Within 1-3 Months', 'Within 1-3 Months'), ('Within 6 Months', 'Within 6 Months'), ('Just Researching', 'Just Researching')], max_length=50)),
                ('enquiry_status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Closed', 'Closed')], max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_ID', models.CharField(default=crm.models.generate_invoice_id, editable=False, max_length=20, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_ref_no', models.CharField(blank=True, max_length=50)),
                ('invoice_tags', models.CharField(blank=True, max_length=100)),
                ('terms_conditions', models.TextField(blank=True)),
                ('invoice_status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('payment_terms', models.CharField(choices=[('Net 15', 'Net 15'), ('Net 20', 'Net 20'), ('Net 45', 'Net 45'), ('Due on Receipt', 'Due on Receipt')], default='Net 30', max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('COD', 'COD'), ('PayPal', 'PayPal')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR'), ('GBP', 'GBP'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('payment_ref_number', models.CharField(blank=True, max_length=50)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoice_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_RETURN_ID', models.CharField(default=crm.models.generate_invoice_return_id, editable=False, max_length=20, unique=True)),
                ('invoice_return_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice_return_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_refund', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_summary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_note_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(max_length=10, unique=True)),
                ('customer_po_referance', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_type', models.CharField(choices=[('Standard', 'Standard'), ('Blanket', 'Blanket'), ('Service', 'Service')], max_length=50)),
                ('quotation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGD', 'SGD')], max_length=3)),
                ('payment_terms', models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60'), ('Advance', 'Advance'), ('COD', 'COD')], max_length=50)),
                ('expected_delivery', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Send', 'Send'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted (SO)', 'Converted (SO)'), ('Expired', 'Expired')], max_length=20)),
                ('revise_count', models.PositiveIntegerField(default=1)),
                ('globalDiscount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shippingCharges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(editable=False, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('revise_history', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_type', models.CharField(choices=[('Standard', 'Standard'), ('Rush', 'Rush'), ('Backorder', 'Backorder')], max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(choices=[('IND', 'IND'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGD', 'SGD')], max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('shipping_method', models.CharField(blank=True, max_length=50)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Submitted(PD)', 'Submitted(PD)'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
