# Generated by Django 4.2.23 on 2025-10-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderhistory',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesordercomment',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesordercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'role__role': 'Sales Representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='masters.product'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='masters.uom'),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationcomment',
            name='person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcomment',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Sales Representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='masters.role'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoicereturnsummary',
            name='invoice_return',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnremark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturnremark',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='serial_numbers',
            field=models.ManyToManyField(blank=True, to='purchase.serialnumber'),
        ),
        migrations.AddField(
            model_name='invoicereturnhistory',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturncomment',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturnattachment',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='sales_order_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='invoiceremark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceremark',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturnremark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturnremark',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='serial_numbers',
            field=models.ManyToManyField(blank=True, to='purchase.serialnumber'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnhistory',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturncomment',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturnattachment',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='invoice_return_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='deliverynoteremark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynoteremark',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='serial_numbers',
            field=models.ManyToManyField(blank=True, to='purchase.serialnumber'),
        ),
        migrations.AddField(
            model_name='deliverynotecustomeracknowledgement',
            name='delivery_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteattachment',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='sales_order_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder'),
        ),
    ]
