# Generated by Django 4.2.23 on 2025-10-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('masters', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteremark',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnoteremark',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnotepaymentrecover',
            name='debit_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recover', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnoteitem',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnoteitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='debitnoteattachment',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.branch'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'department__department_name__icontains': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidate'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='po_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier'),
        ),
        migrations.AddField(
            model_name='creditnoteremark',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnoteremark',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='finance.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnotepaymentrefund',
            name='credit_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refund', to='finance.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='creditnoteattachment',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'department__department_name__icontains': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidate'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoice'),
        ),
    ]
