# Generated by Django 4.2.23 on 2025-10-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('batch_qty', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('PO_date', models.DateField(default=purchase.models.get_default_po_date)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Received', 'Partially Received'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('sales_order_reference', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=50)),
                ('inco_terms', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('notes_comments', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_summary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_file_path', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRN_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField(default=purchase.models.get_default_grn_date)),
                ('supplier_dn_no', models.CharField(blank=True, max_length=100)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('PO_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder')),
                ('qc_done_by', models.ForeignKey(blank=True, limit_choices_to={'department__department_name': 'Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_receipts', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, limit_choices_to={'department__department_name': 'Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('qty_ordered', models.IntegerField(blank=True, null=True)),
                ('qty_received', models.IntegerField()),
                ('accepted_qty', models.IntegerField()),
                ('rejected_qty', models.IntegerField(default=0)),
                ('qty_returned', models.IntegerField(default=0)),
                ('stock_dim', models.CharField(choices=[('None', 'None'), ('Serial', 'Serial'), ('Batch', 'Batch')], default='None', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.stockreceipt')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRN_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField()),
                ('return_date', models.DateField(default=purchase.models.get_default_srn_date)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Returned', 'Partially Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('original_purchased_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_recover', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('GRN_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stockreceipt')),
                ('PO_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder')),
                ('return_initiated_by', models.ForeignKey(blank=True, limit_choices_to={'department__department_name': 'Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('qty_ordered', models.IntegerField(blank=True, null=True)),
                ('qty_rejected', models.IntegerField(blank=True, null=True)),
                ('qty_returned', models.IntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('stock_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stockreceiptitem')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_return_attachments/')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='purchase.stockreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_receipt_attachments/')),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.stockreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumberReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50)),
                ('stock_return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.stockreturnitem')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('stock_receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.stockreceiptitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField()),
                ('insufficient_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='BatchSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.batchnumber')),
            ],
        ),
        migrations.AddField(
            model_name='batchnumber',
            name='stock_receipt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_numbers', to='purchase.stockreceiptitem'),
        ),
    ]
