# Generated by Django 4.2.23 on 2025-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('department', 'role')},
        ),
    ]
