# Generated by Django 4.2.23 on 2025-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_department_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Candidate_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='aadhar_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('phone', 'Phone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='laptop_company_name',
            field=models.CharField(blank=True, choices=[('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personal_number',
            field=models.CharField(max_length=15),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='upload_documents',
        ),
        migrations.AddField(
            model_name='candidate',
            name='upload_documents',
            field=models.ManyToManyField(blank=True, to='core.candidatedocument'),
        ),
    ]
