# Generated by Django 4.2.23 on 2025-08-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='department_name',
        ),
    ]
