# Generated by Django 4.2.23 on 2025-08-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_role_branch_name_remove_role_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assigned_sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.candidate'),
        ),
    ]
